---
- block:
  - apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
  - apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian trusty contrib"
  - apt: name="virtualbox-5.0"
  become: yes
